export type StarterCompany = {
  name: string;
  domain: string;
  website: string;
  careersUrl: string;
  linkedinUrl: string;
  xUrl?: string;
  hqLocation: string;
  tags: string[];
};

export const STARTER_US_TECH_COMPANIES: StarterCompany[] = [
  {
    name: "Stripe",
    domain: "stripe.com",
    website: "https://stripe.com",
    careersUrl: "https://stripe.com/jobs",
    linkedinUrl: "https://www.linkedin.com/company/stripe",
    xUrl: "https://x.com/stripe",
    hqLocation: "South San Francisco, CA",
    tags: ["payments", "fintech"],
  },
  {
    name: "Notion",
    domain: "notion.so",
    website: "https://www.notion.so",
    careersUrl: "https://www.notion.so/careers",
    linkedinUrl: "https://www.linkedin.com/company/notionhq",
    xUrl: "https://x.com/NotionHQ",
    hqLocation: "San Francisco, CA",
    tags: ["productivity"],
  },
  {
    name: "Figma",
    domain: "figma.com",
    website: "https://www.figma.com",
    careersUrl: "https://www.figma.com/careers",
    linkedinUrl: "https://www.linkedin.com/company/figma",
    xUrl: "https://x.com/figma",
    hqLocation: "San Francisco, CA",
    tags: ["design"],
  },
  {
    name: "Vercel",
    domain: "vercel.com",
    website: "https://vercel.com",
    careersUrl: "https://vercel.com/careers",
    linkedinUrl: "https://www.linkedin.com/company/vercel",
    xUrl: "https://x.com/vercel",
    hqLocation: "San Francisco, CA",
    tags: ["frontend", "cloud"],
  },
  {
    name: "Cloudflare",
    domain: "cloudflare.com",
    website: "https://www.cloudflare.com",
    careersUrl: "https://www.cloudflare.com/careers",
    linkedinUrl: "https://www.linkedin.com/company/cloudflare",
    xUrl: "https://x.com/Cloudflare",
    hqLocation: "San Francisco, CA",
    tags: ["infrastructure", "security"],
  },
  {
    name: "Datadog",
    domain: "datadoghq.com",
    website: "https://www.datadoghq.com",
    careersUrl: "https://careers.datadoghq.com",
    linkedinUrl: "https://www.linkedin.com/company/datadog",
    xUrl: "https://x.com/datadoghq",
    hqLocation: "New York, NY",
    tags: ["observability"],
  },
  {
    name: "Shopify",
    domain: "shopify.com",
    website: "https://www.shopify.com",
    careersUrl: "https://www.shopify.com/careers",
    linkedinUrl: "https://www.linkedin.com/company/shopify",
    xUrl: "https://x.com/Shopify",
    hqLocation: "Ottawa, Canada",
    tags: ["commerce"],
  },
  {
    name: "Twilio",
    domain: "twilio.com",
    website: "https://www.twilio.com",
    careersUrl: "https://www.twilio.com/company/jobs",
    linkedinUrl: "https://www.linkedin.com/company/twilio-inc-",
    xUrl: "https://x.com/twilio",
    hqLocation: "San Francisco, CA",
    tags: ["communications"],
  },
  {
    name: "HubSpot",
    domain: "hubspot.com",
    website: "https://www.hubspot.com",
    careersUrl: "https://www.hubspot.com/careers",
    linkedinUrl: "https://www.linkedin.com/company/hubspot",
    xUrl: "https://x.com/HubSpot",
    hqLocation: "Cambridge, MA",
    tags: ["saas", "marketing"],
  },
  {
    name: "Atlassian",
    domain: "atlassian.com",
    website: "https://www.atlassian.com",
    careersUrl: "https://www.atlassian.com/company/careers",
    linkedinUrl: "https://www.linkedin.com/company/atlassian",
    xUrl: "https://x.com/Atlassian",
    hqLocation: "Sydney, Australia",
    tags: ["collaboration"],
  },
  {
    name: "Databricks",
    domain: "databricks.com",
    website: "https://www.databricks.com",
    careersUrl: "https://www.databricks.com/company/careers",
    linkedinUrl: "https://www.linkedin.com/company/databricks",
    xUrl: "https://x.com/databricks",
    hqLocation: "San Francisco, CA",
    tags: ["data", "ai"],
  },
  {
    name: "Snowflake",
    domain: "snowflake.com",
    website: "https://www.snowflake.com",
    careersUrl: "https://careers.snowflake.com",
    linkedinUrl: "https://www.linkedin.com/company/snowflake-computing",
    xUrl: "https://x.com/SnowflakeDB",
    hqLocation: "Bozeman, MT",
    tags: ["data"],
  },
  {
    name: "Coinbase",
    domain: "coinbase.com",
    website: "https://www.coinbase.com",
    careersUrl: "https://www.coinbase.com/careers",
    linkedinUrl: "https://www.linkedin.com/company/coinbase",
    xUrl: "https://x.com/coinbase",
    hqLocation: "New York, NY",
    tags: ["crypto", "fintech"],
  },
  {
    name: "Block",
    domain: "block.xyz",
    website: "https://block.xyz",
    careersUrl: "https://block.xyz/careers",
    linkedinUrl: "https://www.linkedin.com/company/block-xyz",
    xUrl: "https://x.com/Blocks",
    hqLocation: "Oakland, CA",
    tags: ["fintech"],
  },
  {
    name: "Airbnb",
    domain: "airbnb.com",
    website: "https://www.airbnb.com",
    careersUrl: "https://careers.airbnb.com",
    linkedinUrl: "https://www.linkedin.com/company/airbnb",
    xUrl: "https://x.com/Airbnb",
    hqLocation: "San Francisco, CA",
    tags: ["marketplace"],
  },
  {
    name: "Uber",
    domain: "uber.com",
    website: "https://www.uber.com",
    careersUrl: "https://www.uber.com/careers",
    linkedinUrl: "https://www.linkedin.com/company/uber-com",
    xUrl: "https://x.com/Uber",
    hqLocation: "San Francisco, CA",
    tags: ["marketplace"],
  },
  {
    name: "Netflix",
    domain: "netflix.com",
    website: "https://www.netflix.com",
    careersUrl: "https://jobs.netflix.com",
    linkedinUrl: "https://www.linkedin.com/company/netflix",
    xUrl: "https://x.com/netflix",
    hqLocation: "Los Gatos, CA",
    tags: ["media"],
  },
  {
    name: "OpenAI",
    domain: "openai.com",
    website: "https://openai.com",
    careersUrl: "https://openai.com/careers",
    linkedinUrl: "https://www.linkedin.com/company/openai",
    xUrl: "https://x.com/OpenAI",
    hqLocation: "San Francisco, CA",
    tags: ["ai"],
  },
  {
    name: "Anthropic",
    domain: "anthropic.com",
    website: "https://www.anthropic.com",
    careersUrl: "https://www.anthropic.com/careers",
    linkedinUrl: "https://www.linkedin.com/company/anthropicresearch",
    xUrl: "https://x.com/AnthropicAI",
    hqLocation: "San Francisco, CA",
    tags: ["ai"],
  },
  {
    name: "Linear",
    domain: "linear.app",
    website: "https://linear.app",
    careersUrl: "https://linear.app/careers",
    linkedinUrl: "https://www.linkedin.com/company/linear-app",
    xUrl: "https://x.com/linear",
    hqLocation: "San Francisco, CA",
    tags: ["productivity"],
  },
  {
    name: "Convex",
    domain: "convex.dev",
    website: "https://www.convex.dev",
    careersUrl: "https://www.convex.dev/jobs",
    linkedinUrl: "https://www.linkedin.com/company/convex-dev",
    xUrl: "https://x.com/convex_dev",
    hqLocation: "San Francisco, CA",
    tags: ["backend", "realtime"],
  },
  {
    name: "Ramp",
    domain: "ramp.com",
    website: "https://ramp.com",
    careersUrl: "https://ramp.com/careers",
    linkedinUrl: "https://www.linkedin.com/company/ramp",
    xUrl: "https://x.com/ramp",
    hqLocation: "New York, NY",
    tags: ["fintech"],
  },
  {
    name: "Rippling",
    domain: "rippling.com",
    website: "https://www.rippling.com",
    careersUrl: "https://www.rippling.com/careers",
    linkedinUrl: "https://www.linkedin.com/company/rippling",
    xUrl: "https://x.com/rippling",
    hqLocation: "San Francisco, CA",
    tags: ["hr", "saas"],
  },
  {
    name: "Retool",
    domain: "retool.com",
    website: "https://retool.com",
    careersUrl: "https://retool.com/careers",
    linkedinUrl: "https://www.linkedin.com/company/retool",
    xUrl: "https://x.com/retool",
    hqLocation: "San Francisco, CA",
    tags: ["internal-tools"],
  },
];
